### ISSUE TITLE
Develop Methods to Evaluate Poster Designs

### ISSUE THREAD

**Issue by sergiomrebelo** [sergiomrebelo/evo-poster#25]
The objective of this issue is **to develop a set of methods for evaluating the quality of poster designs**. The evaluation process will consider both `mandatory requirements` and a `fitness assignment scheme` to assess each design.

The mandatory requirements include ensuring the readability of the poster design. The fitness assignment scheme includes the aesthetics and semantics of each poster.

### ToDo

The following methods need to be implemented for evaluating poster designs:

- [x] **Method to Evaluate Readability** (see issue #46)
- [x] **Method to Evaluate Layout Semantics** (see issue #54)
- [x]  **Method to Evaluate Design Aesthetics** (see issue #56)
- [x] **Fitness Assignment Scheme:** Develop an **evaluation scheme** that experiments with a stochastic ranking to handle constraint and multi-criteria fitness assignment to handle fitness.
- [x] **Interface:** Update the evolutionary interface to change the weight of fitness

**Comment by sergiomrebelo** [comment]
We develop a fitness assignment scheme that handle with constraints and metrics. Currently, users can define the metrics values in a specific file.

**Comment by sergiomrebelo** [comment]
We have developed an interface to parameterize the fitness assignment function. This allows users to define the features and utilize a method to automatically evolve designs. The new section of the interface has been successfully tested with a Cypress script.
