### ISSUE TITLE
initialization method

### ISSUE THREAD

**Issue by sergiomrebelo** [sergiomrebelo/evo-poster#29]
Develop a method that generates new poster designs randomly at the start of the evolution process. 
 
### ToDo
- [x] define representation and codify genotype (class Poster).
- [x] define Population class and its initialisation methods
- [x] create and initialise posters' grid
- [x] method to initialize background colours styles and define the styles
- [x] method to initialize general typographic features (colours and vertical text align).
- [x] define typefaces and styles

- [x] Render posters in WEBGL
- [x] Verify if styles rendered as expected
- [x] Restrict the typography styles based on typeface
- [x] Poster size not defined as expected [**bug**]
- [x] define the three background styles
- [x] add loaded images on posters
- [x] font loading problem

**Comment by sergiomrebelo** [comment]
The first version of initialisation method is functional, concerning all the identified features as well as the connection with initial interface. It still necessary evaluate the module (see issue #36)
