### ISSUE TITLE
Image Upload

### ISSUE THREAD

**Issue by sergiomrebelo** [sergiomrebelo/evo-poster#3]
This issue is related to users' stories of [Bertie Stack (#1)](https://github.com/sergiomrebelo/evo-poster/wiki/Users'-Stories-and-Scenarios#1--bertie-stark), [Kirsty Frazier #3](https://github.com/sergiomrebelo/evo-poster/wiki/Users'-Stories-and-Scenarios#3--kirsty-frazier), and [Kamil Velez (#5)](https://github.com/sergiomrebelo/evo-poster/wiki/Users'-Stories-and-Scenarios#5--kamil-velez). To evaluatee these users' scenarios the purposed system should allow the input of images, to be included in the poster design and in the typesetting process.

When this issue is closed, the system will allow users to input multiple images into the system, using a dedicated field on the interface.

⚠️ Images files are only loaded into the client-side of the application (as temporary binary files). This system will not save any user information or data during the evolutionary process. ⚠️ 

It should be possible to load images into multiple formats (jpeg, png, etc.).

As unveiled in user's story [#3](https://github.com/sergiomrebelo/evo-poster/wiki/Users'-Stories-and-Scenarios#3--kirsty-frazier), this method should allow users (if they want) to define the position of images on text using the text glyph that they want as anchors (in this case, each image has the same treatment that a text line). [**challenge:** automation]

When not defined, images are placed at random on text and change over evolution [**challenge:** exploration]

The development of these features includes the development of two validation methods:
* validation of the file format;
* validation if the number of anchors and images matchs.

**Note:** Random placement of images is defined in the generator module. In this case, image position will be evolved by system.

### Tasks
- [x] loading multiple image files
- [x] validation of files format (both format and size); [only format]
- [x] divide text by anchors when text division is defined by user
- [ ] divide text by anchors when text division is automatic
