### ISSUE TITLE
Develop a uniform way of the configuration system

### ISSUE THREAD

**Issue by sergiomrebelo** [sergiomrebelo/evo-poster#45]
Currently, the configuration of the system mostly relies on`Params.js`. However, there are instances where some parameters are defined in the code and the current state of the config file is confusing. Thus, this issue addresses the need for the development of a unified way of creating a config file for the system. As documented in users' stories, the system is a multipurpose system. Thus, it is essential to provide users with an easy and fast manner of parametrising the system according to their needs.

**ToDo**
- [x] Review the existing configuration structure and identify inconsistencies or redundancies.
- [x] Define a clear set of parameters that can be customized through the configuration file.
- [x] Test the new configuration system thoroughly to verify its effectiveness and ease of use.
- [x] Provide clear documentation and guidelines on how to utilize the configuration file for users' convenience.
- [x] divide the entry point form `app.js`

**Comment by sergiomrebelo** [comment]
I created `evo-poster.config.js`to replace `Param.js`
