### ISSUE TITLE
Method to Measure Readability (constraints)

### ISSUE THREAD

**Issue by sergiomrebelo** [sergiomrebelo/evo-poster#46]
This issue focuses on creating evaluation metrics to assess the legibility and grid size appropriateness within a poster design container. These metrics will be the constraints in the fitness assignment scheme of the system, ensuring that generated designs satisfy certain readability.

## To-Do List: ##
- [x] **Legibility Measure:** Develop a metric to evaluate whether the text within the poster design fits appropriately within textboxes, avoiding any overset issues. Develop several modes, including one that try to justify the text. 
- [x] **Grid Size Appropriateness Measure:** Create a metric to assess whether the grid size used in the poster design aligns with the container's dimensions, ensuring optimal layout and composition.
- [x] **Define Constraint Evaluation Strategy:** Define a strategy to incorporate the legibility and grid size appropriateness metrics as constraints within the fitness assignment scheme of the system.

**Comment by sergiomrebelo** [comment]
We have implemented and included two constraint metrics, namely legibility and Grid Size Appropriateness Measures. We developed the necessary testing Scripts using Jest. We have implemented a constraint evaluation strategy that employs Stochastic Ranking and a ranking tournament approach. Since we have refactored the tournament method, we modify the tournament method as refer in issue #52. We also have integrated a static penalty method to enable elite evolution, simultaneous to Stochastic Ranking. This method allows us to easier visualise the population increase on the interface. Finally, we develop one Cypress Script for Evolution Testing.
