### ISSUE TITLE
Define system log method

### ISSUE THREAD

**Issue by sergiomrebelo** [sergiomrebelo/evo-poster#51]
The objective of this issue is to define and implement a more robust system log method within our software application. The system log is important to understand how the system works. This way, it is important in all users' stories. You should check external services, such as [Winston](https://github.com/winstonjs/winston), or use localStorage/database to save the logs.

## ToDO
- [x] Log the results to file 
- [ ] Log system running statistics (see [Winston](https://github.com/winstonjs/winston)
- [ ] Review the scope (private or public) of functions, particularly within the controllers scripts.

**Comment by JJ** [comment]
... or mix both. Winston is a log system that can use many kinds of actual "transports", or storage options.

**Comment by sergiomrebelo** [comment]
We utilized a NoSQL database on the backend and inserted the data into it at the end of the generation process. We developed the required methods for this, including a query method to retrieve the records.

**Comment by sergiomrebelo** [comment]
The core part of the issue has been developed. However, the issue was reopened to accommodate two enhancements. 
The plan is to separate it from the current server and create a new one. Additionally, sockets will be implemented to handle requests. A log system has also been established, utilizing a log facilitator method like [Winston](https://github.com/winstonjs/winston).
