### ISSUE TITLE
Evaluate Layout Semantics (measure)

### ISSUE THREAD

**Issue by sergiomrebelo** [sergiomrebelo/evo-poster#54]
This issue focuses on developing semantic layout measures building upon the analysis conducted in the first module of the project. It will prioritise the visibility of the most important parts of the content, considering font size, font weight, font style, and colour. It is a core part of the project, being aligned with all users' stories.

## To-Do List:
- [x] **Semantic Layout Measure:** Develop a metric to evaluate whether the most important parts of a text (the ones which have more relation identified) are valued in layout.
- [x] **Semantic Visual Emphasis Measure:** Create a metric to assess whether the typography features (font, weight and vertical motion) of posters where aligned with the emotional analysis of the content, considering that the most important parts of the content must be the emphasis. Include a **typography crime** mode, which enables penalty designs with too much emphasis.
- [x] #57
- [x] Develop mode **evaluation** test for each metric (using jest).

**Comment by sergiomrebelo** [comment]
The semantic measures have been successfully developed and tested. Although we initially considered this an enhancement, we have chosen to create a lighter version of the `Semantic Visuals Measure`. This version allows users to define a set of color and typographic relationships between the layout's semantics and the visuals through a specific configuration file. While the version is currently in a preliminary stage of development, it justifies the computation required in the input module to facilitate the user's application of an ML approach. Furthermore, this aligns with our prior work on the topic. You create a new issue to further improvement of this measure (#see issue #57)
