### ISSUE TITLE
Improve and refactor mutation method

### ISSUE THREAD

**Issue by sergiomrebelo** [sergiomrebelo/evo-poster#55]
Currently, the mutation method is a uniform method, _i.e._ each gene has the same probability of being changed. During its evolution, it equally modifies genes related to the typesetting of posters (_e.g._ font size) and visuals (_e.g._ background style). Nevertheless, each gene influences the evaluation factors differently, and we have empirically observed that when certain evaluation values are achieved (especially constraint values), there is no necessity for the mutation to still change certain genes too often.

To address this, we propose developing an adaptive mutation method that will enable the system to dynamically adjust gene's mutation probabilities over time. This enhancement will optimize the evolution process and improve the effectiveness of automation tasks with this system. You can find related user stories on automation issues, such as the stories of Jeremy O'Quinn (#2), Kirsty Frazier (#3), and Amelia Chase (#3).

The development of this issue also concerns the refactoring of the mutation method into smaller parts for better maintainability and modularity.

## To-Do List ##

- [ ] Implement the adaptive mutation method in the system, ensuring it modifies the probabilities of each gene over time, based on the current overall evaluation of outputs.
- [ ] Refactor the existing mutation method into smaller, modular parts for better maintainability.
- [ ] Test the overall system performance with the new adaptive mutation approach, comparing it to the previous uniform method.
