### ISSUE TITLE
Method to Evaluate Design Aesthetics (measure)

### ISSUE THREAD

**Issue by sergiomrebelo** [sergiomrebelo/evo-poster#56]
This issue focuses on the development of design aesthetics measures to evaluate the compliance of output designs with the expected aesthetic standards.

The measures will be related to both visual and typography features of the outputs, including text and images. It is acknowledged that output may not fulfil all features simultaneously. The development of these features will include the creation of an interface to select the desired features and their respective weights. This is considered a core part of the project and aligns with all user stories.

## ToDo List

- [x] **Justification:** Estimate whether the text is justified in the poster's space. Inspired by 19th-century posters, the white space on the poster should not be excessive. This metric is very similar to legibly and have two modes: `JUSTIFY` and `ATTEMPT_JUSTIFY`.
- [x] **Alignment**: Estimate if the horizontal alignment of text boxes follows a regular pattern. See [Harrington](https://dl.acm.org/doi/10.1145/1030397.1030419) et al. (2004).
- [x] **Regularity:** Estimate if the vertical alignment of text boxes follows a regular pattern See [Harrington](https://dl.acm.org/doi/10.1145/1030397.1030419) et al. (2004).
- [x]  **Visual Balance:** Estimate the visual balance (centred or left-right) of the composition.  See [Harrington](https://dl.acm.org/doi/10.1145/1030397.1030419) et al. (2004) and [Lopes](https://cdv.dei.uc.pt/balance/) et al. (2023).
- [x] **White Space Fraction:** Check if the white space is in accordance with a predefined value. Traditionally, white space (including margins) should total half of the page area. See [Harrington](https://dl.acm.org/doi/10.1145/1030397.1030419) et al. (2004).
- [x]  **Typeface Paring:** Check if the typeface used on the poster pairs well. It will use measures such as x-size and type of typeface. This may require developing a method to include this information in the system (see issue #45). See [Bringhurst](https://readings.design/PDF/the_elements_of_typographic_style.pdf) (1992) and [Lupton](https://readings.design/PDF/thinkingwithtype_ellenlupton.pdf) (2004)
- [x]  ~**Colour Accessibility:** Check if the colour contrast and luminosity are sufficient to enable the message to be read on a poster.~
- [x] Develop module **evaluation** tests for each metric using jest.

**Comment by sergiomrebelo** [comment]
We remove `Colour Accessibility` metric, making a restriction on the generation of colour schemes. User can define the minimum aceptable constraint value and the amount of attempts in the `evo-poster.config.js` file

**Comment by sergiomrebelo** [comment]
The **Typeface Pairing** measure has been developed with a focus solely on typography classification. It ensures that two different typefaces are not combined within the same line. Therefore, there's no need for the measure to consider combinations involving ascenders, descenders, or x-height measures.

**Comment by sergiomrebelo** [comment]
The **Balance** measure has been developed, taking into consideration multiple balance centres.

**Comment by sergiomrebelo** [comment]
The aesthetic measures have been successfully developed, and we have created the `@evoposter/evaluator` module, which includes a compiled version for ease of use.
